seeds:
  - Activity:
      id: 1
      date: "2021-09-28 00:00:00"
      title: "Bootbar"
      beginsAt: "9:00"
      finishesAt: "12:00"
      remainingSeats: 15
      locationId: 3
  - Activity:
      id: 2
      date: "2021-09-29 00:00:00"
      title: "Bootbar 2"
      beginsAt: "10:00"
      finishesAt: "11:00"
      remainingSeats: 13
      locationId: 1
- Activity:
      id: 3
      date: "2021-09-27 00:00:00"
      title: "Bootbar"
      beginsAt: "9:00"
      finishesAt: "12:00"
      remainingSeats: 15
      locationId: 1
  - Activity:
      id: 4
      date: "2021-09-29 11:00:00"
      title: "Bootbar 2"
      beginsAt: "10:00"
      finishesAt: "11:00"
      remainingSeats: 13
      locationId: 2
