seeds:
  - Activity:
      id: 1
      date: "2021-09-28 00:00:00"
      title: "Bootbar"
      beginsAt: 0
      finishesAt: 180
      remainingSeats: 15
      locationId: 3
  - Activity:
      id: 2
      date: "2021-09-29 00:00:00"
      title: "Bootbar 2"
      beginsAt: 60
      finishesAt: 120
      remainingSeats: 13
      locationId: 1
  - Activity:
      id: 3
      date: "2021-09-27 00:00:00"
      title: "Bootbar"
      beginsAt: 0
      finishesAt: 180
      remainingSeats: 15
      locationId: 1
  - Activity:
      id: 4
      date: "2021-09-29 00:00:00"
      title: "Bootbar 2"
      beginsAt: 60
      finishesAt: 120
      remainingSeats: 13
      locationId: 2
